### ISSUE TITLE
DNAscent detect error

### ISSUE THREAD

**Issue by MiHern** [MBoemo/DNAscent#17] opened 2021-09-06 09:39 UTC
Hi,

I'm trying to use your DNAscent software to call BrdU in Nanopore data we have being producing lately. I have followed you manuals to install and your workflow to map the data and produce the DNAscent index. When running DNAscent detect I got this: 

[>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 140155184243200:
  #000: H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1357 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 298 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 402 in H5PL__find(): can't open directory
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
DNAscent: src/event_handling.cpp:635: void normaliseEvents(read&, bool): Assertion `et.n > 0' failed.
Aborted

I'm don't have a lot of experience in using linux and these tools, so I don't really know what to interpret from that. Do you have idea on what can be causing the errors?

**Comment by MBoemo** [comment] 2021-09-06 10:05
First and foremost, apologies for the lack of an informative error message - I've been meaning to fix this and will do so in the next release.  This error usually arises when DNAscent can't find the fast5 files.  There could be a few reasons for this:
- you don't have read permissions for the fast5 files,
- you've moved the fast5 files to a new directory since building the DNAscent index, 
- you didn't specify the correct directory for the fast5 files when calling DNAscent index.
Those are the first things I'd look at.  If that doesn't solve the problem, let me know and we'll take it from there.

**Comment by MiHern** [comment] 2021-09-06 11:18
Many thanks for the quick answer and the suggestions.

- I have tried given all permissions to the fast5's, still got the error. 
- I noticed I had placed the index in a different folder, but I tried both after moving it to the fast5 folder and deleting it and re-creating it inside the fast5 folder, but nothing changed.
- I think the directory for the fast5 index is correct. I had one doubt here. I'm using only the fast5_pass folder, not the failed ones. When I put the -s option to index with the summary file, it gave me an error that I supposed it was because I had only the fast5_pass, not all, and it had trouble with finding part of the data (fast5_failed).

I have read this in the installation manual "Please note that the high throughput sequencing library (htslib) requires bzlib and lzma for compression. While these are common on most systems, if you don’t have these, apt-get lzma-dev, liblzma-dev, and libbz2-dev. In addition, pfasta requires libbsd on Linux."

Is it possible that I'm missing some of this packages? I'm running it in a server in which I'm not the administrator and I cannot sudo apt-get, so I am not 100% sure they are there. I could ask to install them if any might be creating this issue.

This is my line and the checks at the beginning of DNAscent detect, in case you see something I haven't noticed I'm doing wrong:

~/DNAscent/bin/DNAscent detect -b ~/Nanopore/Col0_BrdU/Col0_BrdU_sorted.bam -r ~/Nanopore/TAIR10_ChrXnames.fa -i ~/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/index.dnascent -o ~/Nanopore/Col0_BrdU/DNAscent/Col0_BrdU_detect
Loading DNAscent index... ok.
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
[>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed: [>                                  ]   0%      0/9973   0hr 0min 0sec  failed:

**Comment by MBoemo** [comment] 2021-09-06 11:23
When you created the bam file, was that made from just the fast5_pass reads?  If so, then just indexing the fast5_pass folder is fine.  If the bam file contains alignments for both passed and failed reads, then that's the issue - when DNAscent looks for the corresponding fast5 folder for a failed read alignment, it can't find it because it wasn't indexed.  

If you did make the bam file from just the passed reads, can you paste the first few lines of index.dnascent here so I can make sure everything looks as it should?

**Comment by MBoemo** [comment] 2021-09-06 11:32
Just as a side note, I would generally recommend running DNAscent on both passed and failed reads from Guppy.  Sometimes high BrdU incorporation can cause a read to fail Guppy's QCs, so if you only run it on passed reads, there's a risk of disproportionately throwing out the reads you're most interested in.  DNAscent will perform it's own QCs to fail any read that doesn't pass its checks.

**Comment by MiHern** [comment] 2021-09-06 11:37
Ok, so that was one of the questions I was going to post later, if you remove the qscore of the basecalling to use all of the reads. Good to know. So you usually pool both fast5 and fastq folders with pass and failed; map everything; sort, index the bam and then index they fast5's, no?. Do you put everything in the same folder? The bam with the fast5 and the dnascent index? By pathing it shouldn't be a problem, but just to try as similar as how you proceed. 

In this case I was only using pass reads for everything, but I'll retry using them all and see if I got the same issue.

These are the first some lines of the index: 

#bulk
000a3bf3-912f-494c-ac89-b3b797886fe2	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
0048941e-9390-4953-95ce-a0f55c838c2d	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
00496793-c0e7-49f7-b5f9-a83f0820762d	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
005ebfab-a7b1-4b68-9b5b-0955cf912d30	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
00781f1f-b8a6-4d8c-9474-9a9996a87531	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
008592b8-b165-462d-9966-01a477e2f042	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
0087309d-75d9-4256-a9c0-1c93b424b210	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
00df0699-ee93-44a5-bf1c-e80e4ce428d7	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
012904bc-c86b-4a4e-bede-0be8012f292c	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
014c6924-bb75-48aa-8947-f7772fc23916	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5
0190141f-63ed-4aa9-98b7-3e5587de729f	/data/home/hernandezm/Nanopore/Col0_BrdU/no_sample/20210902_1718_MC-110706_0_AFO016_5513f312/fast5_pass/AFO016_pass_128dd482_0.fast5

**Comment by MBoemo** [comment] 2021-09-06 11:44
Yes you've got it right, that's what I would recommend.  The index looks fine to me, so it should have been all right with just the fast5_pass, but give it a try on the whole thing and see how it goes.  Also, can I just quickly confirm that you're using R9.4.1 flow cells?

**Comment by MiHern** [comment] 2021-09-06 11:48
Oh, I didn't think about that. I used Flongle flow cells because we had restricted material and we were even short for an ideal Flongle run, orders of magnitude below MinION inputs. Is the data somehow different to the point of not being compatible with your software?

**Comment by MiHern** [comment] 2021-09-06 11:58
I think I'm mixing nomenclature. FLO-FLG001 Flongle flow cells are R.4.1 cells. So there shouldn't be a problem there. Is it possible though that there is some data format difference or something like this between Flongle and MinION that can create problem when running DNAscent?

**Comment by MBoemo** [comment] 2021-09-06 12:07
I've run DNAscent on Flongle data before and didn't have any issues, but not recently or often.  Just to be sure this definitely isn't a file format or software issue, would you mind sending me a single fast5 file (pass or fail, doesn't matter) so I can see if I can reproduce this?  One file should be small enough to use dropbox or equivalent.

**Comment by jts** [comment] 2021-09-06 12:42
It looks like the vbz plugin is missing, try installing from here:

https://github.com/nanoporetech/vbz_compression

**Comment by MBoemo** [comment] 2021-09-06 12:46
Thanks Jared, hadn't spotted that!

**Comment by MiHern** [comment] 2021-09-06 13:05
Many thanks to both! 

I noticed I was making a stupid error when cat the fastq's into one as I were in the same folder and input and output files had the same .fastq extension. I solved that and installed vbz and now it is running.

**Comment by MBoemo** [comment] 2021-09-06 13:06
Glad to hear it - closing for now but give a shout if you have any further issues.

**Closed by MBoemo** 2021-09-06 13:06 UTC

**Comment by MBoemo** [comment] 2021-09-06 14:56
For anyone else with this issue, I've added a documentation section on this (https://dnascent.readthedocs.io/en/latest/installation.html) as of [commit f9b5441](https://github.com/MBoemo/DNAscent/commit/f9b54414a794065be7e243ab447dadf5b5767c1d).
