### ISSUE TITLE
DNAscent detect error: Assertion `scaledEvent > 0.0' failed

### ISSUE THREAD

**Issue by ShuangqiWang** [MBoemo/DNAscent#35] opened 2023-09-14 20:44 UTC
Dear Michael,
When I am running DNAscent detect, I meet an error as follows: 

......
Importing reference... ok.
Opening bam file... ok.
Scanning bam file...ok.
[=====                                   ] 13%
DNAscent: src/alignment.cpp:1536: std::pair<bool, std::shared_ptr<AlignedRead> > eventalign_detect(read&, unsigned int, double): Assertion `scaledEvent > 0.0' failed.
Aborted (core dumped)

The DNAscent detect start but cannot complete. It always stopped at around 13% or 14% progression.
I suspect there might be some problematic lines in my SAM files. So I repeatedly split my SAM files and ran "DNAscent detect" to identify the sections causing the issue. Eventually, I pinpointed a specific line in my SAM file. 
The line is shown as follows: 
695799e9-e8e1-4596-aa98-35140457ba89	2048	chr1	212892622	21	1796H59M1009H	*	0	0	GAGATCAATGTTGCTTTCATGTCTGGAAACACAGCATCCCTTCTGCAGCCCGTGGATCA	==<?<>439::><<<<<?A??<<;=>>A<;<>{><=;<9+,776---,./1568=<=BC	NM:i:0	ms:i:118	AS:i:118	nn:i:0	tp:A:P	cm:i:10	s1:i:56	s2:i:0	de:f:0	SA:Z:chr14,75585331,+,29S932M6I1897S,60,51;chr9,6750385,-,1149S752M3D963S,60,34;chr9,6730566,+,2162S686M5D16S,60,47;chr8,98259140,-,837S178M1849S,3,4;	rl:i:348

I am confused about this line since it seems similar with other lines in the sam file. Interestingly, when I removed this line from sam file and again run DNAscent detect, I encountered the save error as above. 
Could you give me some advance on this question if you know what happened? Thanks a lot!

**Comment by MBoemo** [comment] 2023-09-14 20:58
Sorry about that - my best guess is that this may be due to a bit of bad signal. Would you mind sending me the fast5 file that's causing the issue (` grep 695799e9-e8e1-4596-aa98-35140457ba89' index.dnascent` should show you the file containing this read) and we'll take a look at how best to catch this?

In terms of a quick fix for now, did you remove it from both the sam and the bam file? DNAscent will iterate through the bam file, so it will continue to cause problems if it's still in the bam.

**Comment by ShuangqiWang** [comment] 2023-09-14 23:19
Dear Dr. Boemo,

Thank you so much for your prompt response. I have attached the relevant fast5 file in your email.
Regarding the problematic line: This specific line appears to be the only cause of the DNAscent detect "Aborted (core dumped)" error, as all other split SAM files process without any issues, reaching 100% progression in DNAscent detect.

For the second question: 
Yes, I removed this line from both the sam and bam files. After removing it from sam file, I re-run samtools view/sort/index to generate new bam files. I've double checked the sorted BAM and confirmed that the line was absence.
Interestingly, upon running DNAscent detect, the same error reoccurs when it processes to arround 14%.
DNAscent: src/alignment.cpp:1536: std::pair<bool, std::shared_ptr<AlignedRead> > eventalign_detect(read&, unsigned int, double): Assertion `scaledEvent > 0.0' failed.
Aborted (core dumped)

Thanks for your help!!

**Comment by MBoemo** [comment] 2023-09-15 07:46
Thanks very much for sending the fast5 over. I wasn't able to reproduce this issue using v3.1.2, but I just took a look at your log file and noticed you set `-l 1` which is what's causing the problem. The default is to ignore anything under 1 kb, in part because the software was originally built for long reads, and in part because reads that are extremely short can create problems for DNAscent's in-built alignments and creation of tensors for the deep learning model. Having said that, it's not very good input handling on our part, so we'll fix that for the next release. Closing but reopen if using the default minimum length doesn't fix it.

**Closed by MBoemo** 2023-09-15 07:46 UTC

**Comment by MBoemo** [comment] 2023-11-09 18:22
@dariober my best guess in this case is that you have a corrupted read somewhere, hence why it works for all chromosomes but one when the bam file is split. This happens very rarely, but it's not unheard of. v2.0.2 is also quite dated at this point so it's possible that I fixed whatever's causing this in a subsequent commit. It would be interesting if you pulled from master and ran it on the chromosome in question to see if you get a clean exit.

Also fine to concatenate the results of DNAscent detect when run on split bam files. forkSense won't mind.

**Comment by sergpolly** [comment] 2024-02-09 15:49
we also encounter such an issue quite frequently, in our case it seems to be caused by very short alignments (~several 100 bp) - we have a lot of those - so we had to introduce a quick fix as in #41 -  just to prevent the program crashing when `scaledEvent<=0` happens - maybe this fix would be of help for some

**Comment by MBoemo** [comment] 2024-02-09 16:37
Thanks for pointing this out @sergpolly, we'll wrap this into the next release. Out of curiosity, I'd be interested how you find the performance on such short reads. We hadn't really designed the software for such short alignments and it's possible that some of the scaling might be a bit wonky, but it would be interesting whether that is or isn't the case.
