### ISSUE TITLE
region, forkSense issues

### ISSUE THREAD

**Issue by john-alexander** [MBoemo/DNAscent#12] opened 2021-02-24 11:25 UTC
Dear Michael,

Attaching error logs :
[run.DNAScent.detect_barcode01.927231.err.txt](https://github.com/MBoemo/DNAscent/files/6035509/run.DNAScent.detect_barcode01.927231.err.txt)
[run.DNAScent.detect_barcode02.927232.err.txt](https://github.com/MBoemo/DNAscent/files/6035510/run.DNAScent.detect_barcode02.927232.err.txt)
[run.DNAScent.detect_barcode04.927234.err.txt](https://github.com/MBoemo/DNAscent/files/6035511/run.DNAScent.detect_barcode04.927234.err.txt)
[run.DNAScent.detect_barcode08.927238.err.txt](https://github.com/MBoemo/DNAscent/files/6035512/run.DNAScent.detect_barcode08.927238.err.txt)

We expect BrdU detection in barcodes04-08 though other barcodes might require exceptional handling 

Small files in barcode01/
-rw-r--r-- 1 jalexander01 BCRBIOIN 5.0K Feb 22 10:44 merge.barcode01.fastq
-rw-r--r-- 1 jalexander01 BCRBIOIN 113K Feb 22 10:46 merge.barcode01.sam
-rw-r--r-- 1 jalexander01 BCRBIOIN  32K Feb 22 10:46 merge.barcode01.bam
-rw-r--r-- 1 jalexander01 BCRBIOIN  64K Feb 22 10:46 merge.barcode01.bam.bai
**-rw-r--r-- 1 jalexander01 BCRBIOIN  18K Feb 22 10:46 barcode01.detect**
-rw-r--r-- 1 jalexander01 BCRBIOIN    0 Feb 22 10:46 barcode01.psl
-rw-r--r-- 1 jalexander01 BCRBIOIN  11K Feb 22 10:47 barcode01.forkSense
drwxr-sr-x 3 jalexander01 BCRBIOIN 4.0K Feb 22 10:47 newBedgraphDirectory
_(aborted at region generation)_

And barcode08/
total 3.0G
-rw-r--r-- 1 jalexander01 BCRBIOIN  364M Feb 22 10:44 merge.barcode08.fastq
-rw-r--r-- 1 jalexander01 BCRBIOIN  414M Feb 22 10:48 merge.barcode08.sam
-rw-r--r-- 1 jalexander01 BCRBIOIN  199M Feb 22 10:48 merge.barcode08.bam
-rw-r--r-- 1 jalexander01 BCRBIOIN  1.7M Feb 22 10:48 merge.barcode08.bam.bai
-rw-r--r-- 1 jalexander01 BCRBIOIN 1010M Feb 22 11:40 barcode08.detect
**-rw-r--r-- 1 jalexander01 BCRBIOIN   43M Feb 22 11:41 barcode08.regions**
-rw-r--r-- 1 jalexander01 BCRBIOIN  5.8M Feb 22 11:42 barcode08.psl
-rw-r--r-- 1 jalexander01 BCRBIOIN   23M Feb 22 11:42 barcode08.analogue.psl
-rw-r--r-- 1 jalexander01 BCRBIOIN  998M Feb 22 11:43 barcode08.forkSense
_(aborted at forkSense generation)_

Please let me know.
Kind regards,

John

**Comment by MBoemo** [comment] 2021-02-25 17:07
Can you run `grep '>' barcode01.detect | wc -l` and `grep '>' barcode08.detect | wc -l` and let me know how many reads are in each barcode?

**Comment by john-alexander** [comment] 2021-02-25 17:15
barcode03 	 20
barcode04 	 3
barcode01 	 1
barcode02 	 2
**barcode08 	 8756
barcode05 	 8211
barcode06 	 8223
barcode07	 10046**
unclassified     19507

**Comment by MBoemo** [comment] 2021-02-25 17:26
The regions issue is because you have very few reads in some of these barcodes.  It has to fit some distributions to determine what constitutes a low and high region, so it needs to see at least a few hundred reads in order to do that.  I'll write in something that catches this an exists gracefully with a more informative error message.

For forkSense, I think this is being caused by running it on very short (< ~300 bp) reads but I thought I fixed that in a previous patch - can you run `git log -1` from the DNAscent directory and let me know which commit you're using?

**Comment by john-alexander** [comment] 2021-02-26 09:55
Hi Michael,

That makes sense, thanks.  

Here's git log -1

commit ab844162b9cb707d68714d3c58f5dc8a41b29ae0 (HEAD, tag: 2.0.2)
Author: Michael Boemo <m.a.boemo@gmail.com>
Date:   Tue Nov 10 11:48:05 2020 +0000

    resolve psl issue where the detect header was not properly passed over

**Comment by MBoemo** [comment] 2021-02-26 10:34
This should be fixed in [commit 989ed8f](https://github.com/MBoemo/DNAscent/commit/989ed8f3ab4e6eeaf8ca422a32f4fb5fcc190e7f) - just pull from master and recompile.  Let me know if there are any further issues.

Closing for now, but I'll add better error handling into regions and push an update in the next few days.

**Closed by MBoemo** 2021-02-26 10:34 UTC

**Comment by john-alexander** [comment] 2021-02-26 10:38
Thanks Michael
