### ISSUE TITLE
DNAscent v4 GPU installation

### ISSUE THREAD

**Issue by kmlhpk** [MBoemo/DNAscent#51] opened 2024-05-02 13:08 UTC
I'm trying to install DNAscent v4 into a Singularity container for use on an HPC cluster. Our GPU nodes have CUDA 12.0 driver version 525.105.17. Inside the container, I am installing CUDA 11.8 cuDNN 8.9 as instructed in the DNAscent documentation, but am encountering Tensorflow errors which are preventing DNAscent from executing GPU-accelerated workloads. For example, when trying to run `DNAscent detect` I'm encountering this error:
`2024-04-25 14:22:36.294335: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`
`nvidia-smi` executes fine, so the container can definitely see the host node's GPUs. I've tried CUDA 12.3 and cuDNN 9.1 as well, thinking it was maybe too large a gap between the container's driver version and the host's driver version to maintain back-comp but no luck there either.
I suspect this might be more of a Tensorflow/Singularity problem than a DNAscent problem, but just wondering if you've encountered a similar problem and/or have any advice.

**Comment by MBoemo** [comment] 2024-05-03 17:16
Unfortunately I haven't seen this before but I'd check the device IDs and make sure it lines up with what you're passing on the command line. Closing for now as it sounds like this problem is specific to your setup rather than an issue with the software.

**Comment by kmlhpk** [comment] 2024-05-07 08:44
ok, thanks @MBoemo, I'll keep digging!

**Comment by HrishiDhondge** [comment] 2024-07-17 06:01
@kmlhpk, did you happen to find any solution for this issue? 
I am having a similar problem. I appreciate any help you can provide. 
@MBoemo, do you have any plans to provide the official docker/singularity containers soon?

**Comment by MBoemo** [comment] 2024-07-17 18:37
Sorry we've been so slow with this, we'll try to put something up in the coming week.

**Comment by MBoemo** [comment] 2024-07-23 22:33
@kmlhpk here's a singularity container for our latest release https://cloud.sylabs.io/library/mboemo/dnascent/dnascent

**Comment by kmlhpk** [comment] 2024-07-30 13:50
Hi @MBoemo thanks a lot for this - unfortunately we're still having trouble. Testing on a node with an Nvidia A100, CUDA 12.4, driver version 550.54.15, we encountered the following issue: the command `DNAscent detect -b $bam -r $fasta -i $index -o $output --GPU` returned:

```shell
2024-07-25 16:05:03.861317: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
terminate called after throwing an instance of 'std::logic_error'
   what():  basic_string::_M_construct null not valid
 /ei/software/staging/RCSUPPORT-3720/x86_64/bin/DNAscent: line 8: 726873 Aborted                 (core dumped) singularity exec --nv $DIR/../image.img $(basename "$0") "$@"
```

...while CPU-only execution with `DNAscent detect -b $bam -r $fasta -i $index -o $output` worked fine.

Please could you advise? Seems like an issue with the C++ source code, or maybe with the compilation.

**Comment by MBoemo** [comment] 2024-07-30 15:38
@kmlhpk thanks very much for pointing this out, I'll take a look.

**Comment by MBoemo** [comment] 2024-07-30 16:34
I was able to reproduce this and, interestingly, it looks like part user error and part bug. You've run `DNAscent detect -b $bam -r $fasta -i $index -o $output --GPU` and haven't specified a device number for the GPU (if you need help finding your device number, use nvidia-smi and/or see [this](https://dnascent.readthedocs.io/en/latest/workflows.html) part of the documentation with an example). Under most circumstances, you would have received an error message saying that you haven't specified the device number but there's an input handling issue that happens when `--GPU` is the final argument. I'll fix it. But specify the device number and you should be good to go.

**Closed by MBoemo** 2024-07-30 16:34 UTC

**Comment by kmlhpk** [comment] 2024-07-31 08:22
Great, thank you - my user reports this command now works as expected! Appreciate your swift help on this.
